#!/usr/bin/env node
/**
 * Bundles Chart.js + core/*.js + the card source into one file the HA
 * integration serves as a Lovelace resource. Each core file is dual-UMD
 * (CommonJS for node_helper, `window.WeatherCore.*` global otherwise), so
 * plain concatenation works — no bundler needed.
 *
 * Run after editing core/*.js or card/weather-conditions-card.src.js.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const CORE_FILES = [
  "core/units.js",
  "core/windscale.js",
  "core/visuals.js",
  "core/unitcycle.js",
  "core/render.js",
  "core/charts.js",
  "core/state.js",
  "core/conditions.js",
  "core/soilforecast.js",
];

// Each file is wrapped in its own IIFE so their top-level `const`/`let`
// declarations (e.g. every core file's local `units`/`windscale` alias)
// don't collide when concatenated into one script — only the
// `window.WeatherCore.*` assignments each file makes are shared.
const iife = (src) => `(function () {\n${src}\n})();`;

const chartJs = fs.readFileSync(path.join(ROOT, "vendor", "chart.umd.min.js"), "utf8");
const core = CORE_FILES.map((f) => iife(fs.readFileSync(path.join(ROOT, f), "utf8"))).join("\n");
// The card's <style> lands inside the HA frontend's own document (via
// Shadow DOM), where a relative url() resolves against the *dashboard's*
// URL rather than this file's -- so the embedded copy needs the font at
// its absolute HA static path (registered in
// custom_components/weather_conditions/__init__.py) instead of the
// MM-relative "vendor/..." path the standalone CSS file uses.
const cardCss = fs
  .readFileSync(path.join(ROOT, "MMM-WeatherConditions.css"), "utf8")
  .replace("vendor/weathericons-regular-webfont.woff", "/weather_conditions_static/weathericons-regular-webfont.woff");
let cardSrc = fs.readFileSync(path.join(ROOT, "card", "weather-conditions-card.src.js"), "utf8");
cardSrc = cardSrc.replace("/*__WC_CSS__*/", cardCss.replace(/`/g, "\\`").replace(/\$\{/g, "\\${"));

const bundle = [
  "// GENERATED by scripts/build-card.js — do not edit directly, edit the sources and re-run `npm run build:card`.",
  iife(chartJs),
  core,
  iife(cardSrc),
].join("\n");

const outDir = path.join(ROOT, "custom_components", "weather_conditions", "www");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "weather-conditions-card.js"), bundle);
console.log(`build-card: wrote ${path.relative(ROOT, path.join(outDir, "weather-conditions-card.js"))} (${(bundle.length / 1024).toFixed(0)} KB)`);
